### ISSUE TITLE
Configure IMAP settings

### ISSUE THREAD

**Issue by kennyparsons** [instrumentisto/roundcube-docker-image#10]
I've successfully launched the fpm/nginx image and can reach the roundcube login page. Since roundcube auth is just the IMAP connection, how do I set up the imap settings prior to logging in?

**Comment by tyranron** [comment]
@kennyparsons hi, consider [upstream's Wikis](https://github.com/roundcube/roundcubemail/wiki/Configuration#imap-server-connection) for this.

Here is an example of our configuration used in Kubernetes Pod:
```php
<?php
$config = [];

$config['db_dsnw'] = 'sqlite:////var/db/roundcube.db?mode=0640';

$config['default_host'] = 'tls://127.0.0.1';
$config['default_port'] = 143;
$config['imap_conn_options']['ssl'] = [
    'verify_peer' => false,
     'verify_peer_name' => false,
];

$config['smtp_server'] = 'tls://127.0.0.1';
$config['smtp_port'] = 587;
$config['smtp_user'] = '%u';
$config['smtp_pass'] = '%p';
$config['smtp_conn_options']['ssl'] = [
    'verify_peer' => false,
    'verify_peer_name' => false,
];

$config['des_key'] = 'Change_me_I_am_example!!';
```

The way to mount the config file is [described in README](https://github.com/instrumentisto/roundcube-docker-image/tree/1.4.11-r4#how-to-use-this-image).
