### ISSUE TITLE
CI build fails for <= 1.4

### ISSUE THREAD

**Issue by waja** [instrumentisto/roundcube-docker-image#13]
`composer` fails to install software, see https://github.com/instrumentisto/roundcube-docker-image/runs/7234506982?check_suite_focus=true#step:5:2750 for example.

**Comment by tyranron** [comment]
@waja [fixed](https://github.com/instrumentisto/roundcube-docker-image/commit/c574467d2ba871b79b3f29a782fef3d04f2478ef).
