### ISSUE TITLE
HTTPs

### ISSUE THREAD

**Issue by cnaslain** [instrumentisto/roundcube-docker-image#2]
Hi,
First of all, thanks for working on ths application; that's great to get such image with a working roundcube.
I have a question: Is there any configuration option to use this image with HTTPs enabled? Do I have to add/modify my own apache2 config files + SSL certificates?
Regards,
Chris

**Comment by tyranron** [comment]
@cnaslain if you are using `fpm` version Docker image then no, as whole SSL/TLS configuration is on Nginx that is used in conjuction with this image.  
If you're using `apache` version Docker image, then you need to provide SSL/TLS configuration and certificates/keys inside container (mount them, for example).

**Comment by cnaslain** [comment]
Thanks for the feedback. I solve this by creating a new Dockerfile to enable SSL:

FROM instrumentisto/roundcube
RUN a2enmod ssl && \
    a2ensite default-ssl

Then create self signed certs and add volumes to match default apache2 SSL configuration + custom roundcube configuration:
      volumes:
        - ./roundcube/config.inc.php:/app/config/config.inc.php:ro
        - /etc/pki/tls/certs/roundcube.crt:/etc/ssl/certs/ssl-cert-snakeoil.pem
        - /etc/pki/tls/private/roundcube.key:/etc/ssl/private/ssl-cert-snakeoil.key

It does work well :-)
