### ISSUE TITLE
RC 1.3: No gpg installed

### ISSUE THREAD

**Issue by bratkartoffel** [instrumentisto/roundcube-docker-image#4]
Hi,

the current docker image (roundcube 1.3) is missing the gpg binary, thus the "enigma" plugin fails to load.
This is results in an "Service unavailable", 600-Error when viewing encrypted / signed mails.

Please add an "apt-get install gpg" to the Dockerfile.

Thanks,
Simon

**Comment by tyranron** [comment]
@bratkartoffel [done](https://github.com/instrumentisto/roundcube-docker-image/commit/1dc07b84b41ae85f0eb1f5b8a95aeca03795b686).
